workspace:
  base: /go
  path: src/github.com/amarburg/cgo-movieset

pipeline:
  build:
    image: amarburg/golang-ffmpeg
    commands:
      - go get -t -v
      - go build
      - go test
      - make test

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status:
        - success
        - failure
