workspace:
  base: /go
  path: src/github.com/amarburg/cgo-movieset

pipeline:
  build:
    image: amarburg/golang-ffmpeg:latest-ci
    pull: true
    commands:
      - go get -t -v
      ## Megacheck will call out many "unused" functions in exported API
      - golangci-lint run --disable megacheck
      - go build
      - go test
      - make test

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status:
        - success
        - failure
